# Generated by Django 4.2.7 on 2025-12-15 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Home', 'Home'), ('Flat / Apartment', 'Flat / Apartment'), ('Land', 'Land'), ('Commercial Land', 'Commercial Land'), ('Plot', 'Plot'), ('Farm Land', 'Farm Land'), ('Warehouse', 'Warehouse'), ('Shop', 'Shop')], max_length=50)),
                ('city', models.CharField(max_length=200)),
                ('khasra_number', models.CharField(max_length=100)),
                ('full_address', models.TextField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=15)),
                ('size_unit', models.CharField(choices=[('sq ft', 'sq ft'), ('sq yard', 'sq yard'), ('acre', 'acre')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('On Hold', 'On Hold')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='properties__city_74fa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties__propert_5c7790_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties__status_6427a0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['khasra_number'], name='properties__khasra__eadfd3_idx'),
        ),
    ]
